#!/usr/bin/env bash

dir=$(pwd)
lasteditedfile=$(find . -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
target=${lasteditedfile:2}

a=":cd $dir | :buffer $latest"

find . -type f \( \
-iname "*html" \
-o -iname "*htm" \
-o -iname "*php" \
-o -iname "*css" \
-o -iname "*js" \
-o -iname "*htaccess" \
\) -exec vim -c "$a" {} +
